# version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  web:
    build:
      context: .
      dockerfile: Dockerfile # Dockerfile is in the current directory
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=CourseManagementDb;User Id=sa;Password=YourStrong!Passw0rd;
    depends_on:
      - db

volumes:
  mssql_data: